spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING.DATASOURCE.URL}
    username: ${SPRING.DATASOURCE.USERNAME}
    password: ${SPRING.DATASOURCE.PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${SERVER_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA.CLIENT.SERVICE_URL.DEFAULT_ZONE}
  instance:
    instance-id: ${spring.application.name}:${server.port}


